- when: ansible_distribution == "Archlinux"
  block:
    - name: Clone Yay AUR
      git:
        repo: "{{ yay_aur_url }}"
        dest: "{{ yay_build_path }}"

    - name: Build Yay AUR
      shell: makepkg -si --noconfirm
      args:
        chdir: "{{ yay_build_path }}"
