- name: Configure ~/.bash_aliases
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.bash_aliases"
    block: "{{ lookup('file', 'bash_aliases') }}"
    marker: "# {mark} ANSIBLE ALIASES BLOCK"
    create: true
    mode: "0644"
  tags:
    - user_config
