- name: Install Restic
  become: true
  ansible.builtin.package:
    state: present
    name: restic

- name: Install fuse
  become: true
  ansible.builtin.package:
    state: present
    name: fuse2

- name: Create user systemd folder
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user"
    state: directory
    mode: "0755"
  tags:
    - user_config

- name: Remove old service files
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user/{{ item }}"
    state: absent
  loop:
    - clean_backups.service
    - clean_backups.timer
  tags:
    - user_config

- name: Copy service files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/{{ item }}"
    mode: "0644"
  loop:
    - clean_backups@.service
    - clean_backups@.timer
  tags:
    - user_config

- name: Copy clean_backups script
  ansible.builtin.copy:
    src: clean_backups
    dest: "{{ ansible_env.HOME }}/.local/bin/"
    mode: "0755"
  tags:
    - user_config
