- name: Install Restic
  become: true
  ansible.builtin.package:
    state: present
    name: restic

- name: Install fuse
  become: true
  ansible.builtin.package:
    state: present
    name: fuse2

- name: Create user systemd folder
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user"
    state: directory
    mode: "0755"

- name: Copy service files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/{{ item }}"
    mode: "0644"
  loop:
    - clean_backups.service
    - clean_backups.timer

- name: Copy clean_backups script
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/"
    mode: "0755"
  loop:
    - clean_backups
    - clean_host_backups

- name: Enable clean_backups timer
  ansible.builtin.systemd:
    name: clean_backups.timer
    daemon_reload: true
    enabled: true
    scope: user
