- name: Install Restic
  become: true
  ansible.builtin.package:
    state: present
    name: restic

- name: Create user systemd folder
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user"
    state: directory
    mode: 0755

- name: Copy service files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/{{ item }}"
    mode: 0644
  loop:
    - clean_backups.service
    - clean_backups.timer

- name: Create user local bin
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: 0755

- name: Copy clean_backups script
  ansible.builtin.copy:
    src: clean_backups
    dest: "{{ ansible_env.HOME }}/.local/bin/"
    mode: 0755

- name: Enable clean_backups timer
  ansible.builtin.systemd:
    name: clean_backups.timer
    enabled: true
    scope: user
