#!/bin/bash

# Exit on failure with status code of failed command
set -e

[ -z "$RESTIC_REPO_PATH" ] && RESTIC_REPO_PATH="/data/restic"
[ -z "$RESTIC_PASSWORD_PATH" ] && RESTIC_PASSWORD_PATH="$HOME/.restic_pass"

[ -z "$KEEP_HOURLY" ] && KEEP_HOURLY=3
[ -z "$KEEP_DAILY" ] && KEEP_DAILY=7
[ -z "$KEEP_WEEKLY" ] && KEEP_WEEKLY=5
[ -z "$KEEP_MONTHLY" ] && KEEP_MONTHLY=12
[ -z "$KEEP_YEARLY" ] && KEEP_YEARLY=50

[ -z "$CLEAN_TAG" ] && CLEAN_TAG="auto"
[ -z "$CLEAN_HOST" ] && CLEAN_HOST="tom-pc"

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo "Usage: $0 [-h|--help]"
    echo
    echo "Clean old snapshots for the given tag. The snapshots will be"
    echo "filtered by tags using the CLEAN_TAG and CLEAN_HOST environment"
    echo "variable. The default tag is auto. See the script file for the"
    echo "environment variables and their default values."
    echo
    echo "Current variables are"
    echo
    echo "RESTIC_REPO_PATH is $RESTIC_REPO_PATH"
    echo "RESTIC_PASSWORD_PATH is $RESTIC_PASSWORD_PATH"
    echo "KEEP_HOURLY is $KEEP_HOURLY"
    echo "KEEP_DAILY is $KEEP_DAILY"
    echo "KEEP_WEEKLY is $KEEP_WEEKLY"
    echo "KEEP_MONTHLY is $KEEP_MONTHLY"
    echo "KEEP_YEARLY is $KEEP_YEARLY"
    echo "CLEAN_TAG is $CLEAN_TAG"
    echo "CLEAN_HOST is $CLEAN_HOST"

    exit 1
fi

START_SECONDS=$SECONDS

RED="\e[0;31m"
GREEN="\e[0;32m"
YELLOW="\e[0;33m"
CYAN="\e[0;36m"
WHITE="\e[1;97m"
RESET="\e[0;0m"

echo -e "${CYAN}:: ${RESET}Cleaning backups for" \
    "${WHITE}Tag ${YELLOW}$CLEAN_TAG${WHITE}" \
    "${WHITE}Host ${YELLOW}$CLEAN_HOST${WHITE}" \
    "${WHITE}Repo ${GREEN}$RESTIC_REPO_PATH${RESET}"

echo -e "${CYAN}:: ${RESET}Keeping last" \
    "${RED}$KEEP_HOURLY${RESET} hourly" \
    "${RED}$KEEP_DAILY${RESET} daily" \
    "${RED}$KEEP_WEEKLY${RESET} weekly" \
    "${RED}$KEEP_MONTHLY${RESET} monthly" \
    "${RED}$KEEP_YEARLY${RESET} yearly" \
    "${RESET}"

restic -v \
    -p "$RESTIC_PASSWORD_PATH" \
    -r "$RESTIC_REPO_PATH" \
    forget \
    --prune \
    --tag "$CLEAN_TAG" \
    --host "$CLEAN_HOST" \
    --keep-hourly "$KEEP_HOURLY" \
    --keep-daily "$KEEP_DAILY" \
    --keep-weekly "$KEEP_WEEKLY" \
    --keep-monthly "$KEEP_MONTHLY" \
    --keep-yearly "$KEEP_YEARLY"

echo -e "${CYAN}:: ${WHITE}Finished in $((SECONDS - START_SECONDS))s!${RESET}"
