- name: Install bash
  become: true
  ansible.builtin.package:
    name: bash
    state: present

- name: Get default shell
  ansible.builtin.command: echo "$SHELL"
  changed_when: false
  register: shell

- name: Make bash default shell
  become: true
  ansible.builtin.command: chsh -s /bin/bash
  when: shell.stdout != "/bin/bash"
