- name: Install Apprise
  become: true
  ansible.builtin.package:
    state: present
    name: apprise

- name: Install mail_stats
  ansible.builtin.command: pipx install git+https://github.com/automas-dev/mail_status.git

- name: Create user systemd folder
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user"
    state: directory
    mode: "0755"

- name: Copy service files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/{{ item }}"
    mode: "0644"
  loop:
    - mail_stats.service
    - mail_stats.timer

- name: Copy script
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/"
    mode: "0755"
  loop:
    - mail_system_report

- name: Enable service timer
  ansible.builtin.systemd:
    name: mail_stats.timer
    daemon_reload: true
    enabled: true
    scope: user
