#!/bin/bash

# Exit on failure with status code of failed command
set -e

if [ -z "$HOSTNAME" ]; then
    echo "environment variable HOSTNAME is empty, cannot continue"
    exit 1
fi

if [ -z "$REMOTE_HOST" ]; then
    REMOTE_HOST="tom-lan.local"
fi

if [ -z "$REMOTE_PATH" ]; then
    REMOTE_PATH="/home/deepraid/restic"
fi

START_SECONDS=$SECONDS

RED="\e[0;31m"
GREEN="\e[0;32m"
YELLOW="\e[0;33m"
CYAN="\e[0;36m"
WHITE="\e[1;97m"
RESET="\e[0;0m"

echo -e "${CYAN}:: ${WHITE}Backing up\
    ${YELLOW}$HOSTNAME${WHITE}:${GREEN}$HOME${WHITE}\
    to ${YELLOW}$REMOTE_HOST${WHITE}:${GREEN}/home/deepstorage/restic${RESET}"

notify-send -u low -t 30000 "Backup has started..."

tries=3

while [ $tries > 3 ] && !\
    restic -v\
        -p $HOME/.restic_pass\
        -r sftp:$REMOTE_HOST:$REMOTE_PATH\
        backup\
        --exclude-file $HOME/.restic_exclude\
        $HOME\
        --tag $HOSTNAME
do
    echo "Failed, retrying"
    sleep 1
    let tries-=1
done

echo -e ${CYAN}:: ${WHITE}Finished in $(( SECONDS - START_SECONDS ))s!${RESET}

notify-send -u low "Backup has finished!"
