#!/usr/bin/env python3

import sys

# pip install --user pyserial
from serial.tools.list_ports import comports

keys = ['description', 'device', 'device_path', 'hwid', 'interface', 'location', 'manufacturer', 'name',
        'pid', 'product', 'serial_number', 'subsystem', 'usb_device_path', 'usb_interface_path', 'vid']

#ports = comports()
#keys = list(filter(lambda a: not a.startswith('_'), dir(ports[0])))
#print('keys', keys)


def print_usage():
    print('Usage:', sys.argv[0], '[options]')
    print('    -h --help     Display usage')
    print('    -v --verbose  Verbose output')


if __name__ == '__main__':
    verbose = False

    for arg in sys.argv[1:]:
        if arg == '-h' or arg == '--help':
            print_usage()
            exit()
        elif arg == '-v' or arg == '--verbose':
            verbose = True
        else:
            print('Unknown flag', arg)
            print_usage()
            exit(1)

    print("Serial devices:")
    for port in comports():
        print(port)
        if verbose:
            for key in keys:
                print('   ', key, ':', repr(getattr(port, key)))
            print()
