#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: $0 <path> [store_path]"
fi

LINUX_CONF="$(pwd $0)"

# add_install ~/.bashrc
# > mv ~/.bashrc bashrc
# > try_install bashrc

# add_install ~/.config/termite config/termite
# > mv ~/.config/termite config/termite
# > try_install config/termite ~/.config/termite

do_install() {
    TO_ADD=$1
    STORE_PATH=$2
    INSTALL_ARGS=$3
    echo mv $TO_ADD $STORE_PATH
    echo try_install $INSTALL_ARGS

    mv $TO_ADD $STORE_PATH
    echo try_install $INSTALL_ARGS >> $(pwd $0)/install
}

if [ -z "$2" ]; then
    TO_ADD="$1"
    STORE_PATH="$(basename $1)"

    if [[ "$STORE_PATH" = .* ]]; then
        STORE_PATH="${STORE_PATH:1}"
    fi

    if [ -e $STORE_PATH ]; then
        echo "Store path $STORE_PATH already exists!"
        exit 1
    fi

    do_install $TO_ADD $STORE_PATH "$STORE_PATH"
else
    TO_ADD="$1"
    STORE_PATH="$2"

    if [ -e $STORE_PATH ]; then
        echo "Store path $STORE_PATH already exists!"
        exit 1
    fi

    do_install $TO_ADD $STORE_PATH "$STORE_PATH $TO_ADD"
fi

