#!/usr/bin/env ansible-playbook
- name: Install User
  hosts: localhost
  roles:
    - local_bin
    - ssh_keygen
    - no_sudo_password
    - bash_config
    - project_templates
    - gitprompt
    - backup_client
