#!/bin/bash

try_install() {
	TO_INSTALL=$1
	INSTALL_TO=$2

	if [ -z "$INSTALL_TO" ]; then
		INSTALL_TO="$HOME/.$TO_INSTALL"
	fi

    TO_INSTALL="$(pwd ./)/$TO_INSTALL"

	if [ -L $INSTALL_TO ]; then
		echo Warning: Symbolic link already exists: $INSTALL_TO
	elif [ -d $INSTALL_TO ]; then
		echo Warning: Directory already exists: $INSTALL_TO
	elif [ -f $INSTALL_TO ]; then
		echo Warning: File already exists: $INSTALL_TO
	else
        ln -s $TO_INSTALL $INSTALL_TO
		echo Link created for $TO_INSTALL at $INSTALL_TO
	fi
}

try_install bashrc
try_install gdbinit
try_install gitconfig
try_install scripts
try_install vimrc
try_install LESS_TERMCAP
try_install Xdefaults
try_install Xdefaults ~/.Xresources
try_install Xmodmap
try_install config/nvim
try_install backup_exclude
try_install astylerc

echo Done!
exit 0

