#!/usr/bin/env ansible-playbook

- name: Install System
  hosts: server
  roles:
    - server/packages
    - packages/git
    - packages/yay
    - packages/docker
    - packages/python
    - packages/bash

    - server/ddns
    - server/raid

    - server/user/github
    - server/user/colleen
    # - backup/server
    # - mail_system_report

    - role: bash_config
      tags:
        - user_config

  vars:
    ddclient_zone: twhps.net
    ddclient_hosts:
      - twhps.net
      - api.twhps.net
      # - home.twhps.net
      - public.twhps.net
      - souprfood.com
