#!/usr/bin/env ansible-playbook
- name: Install System
  hosts: server
  roles:
    - server_packages
    - git
    - yay
    - docker
    - python
    - bash

- name: Install Extra
  host: server
  roles:
    - ddns
    - server_user_github
    # - backup_server
    # - mail_system_report

- name: Configure
  hosts: server
  roles:
    - bash_config
  tags:
    - user_config