#!/usr/bin/env ansible-playbook
- name: Install Base
  hosts: localhost
  roles:
    - pacman_conf
    - update_keyring
    - packages
    - yay
    - docker
    - python
    - rust
    - node
    - ansible
    - neovim
    - bash
    - wine
