#!/usr/bin/env ansible-playbook
- name: Import Install Base
  import_playbook: install_base.yaml

- name: Import Install Desktop
  import_playbook: install_desktop.yaml

- name: Install User
  hosts: localhost
  roles:
    - ssh_keygen
    - no_sudo_password
    - bash
    - project_templates
