#!/usr/bin/env ansible-playbook

- name: Gather facts about localhost
  hosts: localhost

- name: Install System
  hosts: server
  roles:
    - server/packages

    - packages/git
    - packages/docker
    - packages/python
    - packages/bash

    - server/ddns
    - server/raid

    - server/user/github
    - server/user/colleen

    # Needs rewrite to remove restic user
    # or maybe not? /data has raid user owning files from last install
    # - backup/server
    # - mail_system_report

    - role: bash_config
      tags:
        - user_config

  vars:
    raid_user: data
    ddclient_zone: twhps.net
    ddclient_hosts:
      - twhps.net
      - api.twhps.net
      # - home.twhps.net
      - public.twhps.net
      - souprfood.com
