#!/usr/bin/env ansible-playbook

- name: Install System
  hosts: server
  roles:
    - server_packages
    - git
    - yay
    - docker
    - python
    - bash

- name: Setup RAID
  host: server
  roles:
    - server/raid
    # - server/raid_assemble

- name: Install Extra
  hosts: server
  roles:
    - server/user/github
    - server/user/colleen
    # - backup/server
    # - mail_system_report

- name: Install DDNS
  hosts: server
  vars:
    ddclient_zone: twhps.net
    ddclient_hosts:
      - twhps.net
      - api.twhps.net
      # - home.twhps.net
      # - minecraft.twhps.net
      - public.twhps.net
      # - torc.twhps.net
      - souprfood.com
  roles:
    - ddns

- name: Configure
  hosts: server
  roles:
    - bash_config
  tags:
    - user_config
