#!/usr/bin/env ansible-playbook
- name: Install Desktop
  hosts: localhost
  roles:
    - xorg
    - i3
    - plasma
    - desktop_apps
    - bluetooth
    - fonts
    - desktop_config
    - termite
    - blender
