#!/usr/bin/env ansible-playbook

- name: Talk to all hosts just so we can learn about them
  hosts: localhost
  tasks:
    - name: Classify hosts depending on their OS distribution
      ansible.builtin.group_by:
        key: os_{{ ansible_facts['distribution'] }}

- hosts: os_Archlinux
  gather_facts: False
  roles:
    - pacman_conf
    - update_keyring

- name: Install
  hosts: localhost
  roles:
    # Base
    - packages/base
    - packages/git
    - packages/yay

    # System
    - packages/docker
    - packages/python
    - packages/ansible
    - packages/bash
    - packages/pyenv
    - packages/pipx
    - packages/pipx_poetry
    - packages/qemu

    # Desktop
    # - desktop/fonts
    - desktop/config

    # Desktop Applications
    # - apps/blender
    # - apps/arduino
    - apps/appimage_launcher
    - apps/gnome-terminal
    - apps/google-chrome
    - apps/inkscape
    - apps/play_on_linux
    - apps/virtualbox
    - apps/vscode
    - apps/webots

    # User
    - local_bin
    - ssh_keygen
    - no_sudo_password
    - bash_config
    - project_templates
    - gitprompt
    #- backup/client

    #- name: Enable backups
    #  hosts: tom-lan
    #  vars:
    #    restic_public_key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_ed25519.pub') }}"
    #  roles:
    #    - backup_server_add_user_key
    #  tags:
    #    - never
    #    - enable_backups
