#!/usr/bin/env ansible-playbook
- name: Install System
  hosts: localhost
  roles:
    - docker
    - python
    - python_extra
    - rust
    - node
    - ansible
    - neovim
    - bash
    - wine
    - bazel
    - reflector
