#!/usr/bin/env ansible-playbook
- name: Install Base
  hosts: localhost
  roles:
    - pacman_conf
    - packages/base
    - packages/git
    - packages/yay
  tags:
    - base

- name: Install System
  hosts: localhost
  roles:
    - packages/docker
    - packages/python
    - packages/python_extra
    - packages/rust
    - packages/node
    - packages/ansible
    - packages/neovim
    - packages/bash
    - packages/wine
    - packages/bazel
    - packages/reflector
  tags:
    - system

- name: Install Desktop
  hosts: localhost
  roles:
    - packages/xorg
    - desktop/i3
    - desktop/plasma
    - desktop/apps
    - packages/bluetooth
    - desktop/fonts
    - desktop/config
    - apps/alacritty
    - apps/blender
  tags:
    - desktop

- name: Install User
  hosts: localhost
  roles:
    - local_bin
    - ssh_keygen
    - no_sudo_password
    - bash_config
    - project_templates
    - gitprompt
    - backup/client
  tags:
    - user_config

- name: Enable backups
  hosts: tom-lan
  vars:
    restic_public_key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_ed25519.pub') }}"
  roles:
    - backup_server_add_user_key
  tags:
    - never
    - enable_backups
