#!/usr/bin/env ansible-playbook
- name: Install
  hosts: localhost
  vars:
    apt_packages:
      - wget
      - curl
      - git
      - vim
      - neofetch
      - xclip
      - fzf
      - python3
      - python-is-python3
      - python3-psutil
    snap_packages:
      - firefox
      - gimp
      - vlc
      - spotify
    snap_classic_packages:
      - code
      - htop
      - nvim

  tasks:
    - name: Install apt packages
      become: true
      package:
        state: latest
        name: "{{ apt_packages }}"
      tags:
        - packages

    - name: Install snap packages
      become: true
      snap:
        state: present
        name: "{{ snap_packages }}"
      tags:
        - desktop

    - name: Install snap classic packages
      become: true
      snap:
        state: present
        classic: true
        name: "{{ snap_classic_packages }}"
      tags:
        - desktop

    - name: Generate SSH Key
      shell: ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
      args:
        creates: ~/.ssh/id_rsa
      tags:
        - user

    - name: Disable sudo for current user
      become: true
      lineinfile:
        path: "/etc/sudoers.d/{{ ansible_user_id }}"
        create: yes
        line: "{{ ansible_user_id }} ALL=(ALL) NOPASSWD: ALL"
      tags:
        - user

    - name: Keyboard repeat interval
      shell: |
        gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 30
      tags:
        - user

    - name: Keyboard repeat delay
      shell: |
        gsettings set org.gnome.desktop.peripherals.keyboard delay 270
      tags:
        - user
