#!/usr/bin/env ansible-playbook
- name: Install Base
  hosts: localhost
  roles:
    - pacman_conf
    - packages
    - git
    - yay

- name: Install System
  hosts: localhost
  roles:
    - docker
    - python
    - python_extra
    - rust
    - node
    - ansible
    - neovim
    - bash
    - wine
    - bazel
    - reflector

- name: Install Desktop
  hosts: localhost
  roles:
    - xorg
    - i3
    - plasma
    - desktop_apps
    - bluetooth
    - fonts
    - desktop_config
    - alacritty
    - blender

- name: Install User
  hosts: localhost
  roles:
    - local_bin
    - ssh_keygen
    - no_sudo_password
    - bash_config
    - project_templates
    - gitprompt
    - backup_client
  tags:
    - user_config
