#!/usr/bin/env ansible-playbook
- name: Install Base
  hosts: localhost
  roles:
    - pacman_conf
    - packages
    - git
    - yay
  tags:
    - base

- name: Install System
  hosts: localhost
  roles:
    - docker
    - python
    - python_extra
    - rust
    - node
    - ansible
    - neovim
    - bash
    - wine
    - bazel
    - reflector
  tags:
    - system

- name: Install Desktop
  hosts: localhost
  roles:
    - xorg
    - i3
    - plasma
    - desktop_apps
    - bluetooth
    - fonts
    - desktop_config
    - alacritty
    - blender
  tags:
    - desktop

- name: Install User
  hosts: localhost
  roles:
    - local_bin
    - ssh_keygen
    - no_sudo_password
    - bash_config
    - project_templates
    - gitprompt
    - backup/client
  tags:
    - user_config

- name: Enable backups
  host: tom-lan
  vars:
    restic_public_key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_ed25519.pub') }}"
  roles:
    - backup_server_add_user_key
  tags:
    - never
    - enable_backups
