#!/usr/bin/env ansible-playbook
- name: Import Install Base
  import_playbook: install_base.yaml

- name: Install Desktop
  hosts: localhost
  roles:
    - xorg
    - i3
    - plasma
    - desktop_apps
    - bluetooth
    - fonts
    - desktop_config
    - termite
