#!/bin/bash

function light() {
    . ~/.scripts/change_theme light
}

function gray() {
    . ~/.scripts/change_theme gray
}

function dark() {
    . ~/.scripts/change_theme dark
}

export BACKGROUND=$(cat ~/.last_background)
export -f light
export -f gray
export -f dark


