#!/usr/bin/env ansible-playbook

- name: Talk to all hosts just so we can learn about them
  hosts: localhost
  tasks:
    - name: Classify hosts depending on their OS distribution
      ansible.builtin.group_by:
        key: os_{{ ansible_facts['distribution'] }}

- hosts: os_Archlinux
  gather_facts: False
  tasks:
    # Tasks for CentOS hosts only go in this play.
    - name: Ping my CentOS hosts
      ansible.builtin.ping:

- hosts: os_Ubuntu
  gather_facts: False
  tasks:
    # Tasks for CentOS hosts only go in this play.
    - name: Ping my CentOS hosts
      ansible.builtin.ping:
