- name: Update Apt Repositories
  become: true
  apt:
    update_cache: true
  changed_when: false
  when: ansible_distribution == "Ubuntu"

- name: Install Base Packages
  become: true
  package:
    state: latest
    name: "{{ packages.base }}"

- name: Install Extra Packages
  become: true
  package:
    state: latest
    name: "{{ packages.extra }}"
  tags: extra

- name: Install Ubuntu Packages
  become: true
  package:
    state: latest
    name: "{{ packages.ubuntu }}"
  when: ansible_distribution == "Ubuntu"

- name: Install Archlinux Packages
  become: true
  package:
    state: latest
    name: "{{ packages.archlinux }}"
  when: ansible_distribution == "Archlinux"
