- name: Update Apt Repositories
  become: true
  ansible.builtin.package:
    update_cache: true
  changed_when: false
  when: ansible_distribution == "Ubuntu"

- name: Install All Base Packages
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ packages.all.base }}"

- name: Install All Extra Packages
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ packages.all.extra }}"
  tags: extra

- name: Install Ubuntu Base Packages
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ packages.ubuntu.base }}"
  when: ansible_distribution == "Ubuntu"

- name: Install Ubuntu Extra Packages
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ packages.ubuntu.extra }}"
  when: ansible_distribution == "Ubuntu"
  tags: extra

- name: Install Archlinux Base Packages
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ packages.archlinux.base }}"
  when: ansible_distribution == "Archlinux"

- name: Install Archlinux Extra Packages
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ packages.archlinux.extra }}"
  when: ansible_distribution == "Archlinux"
