# Makefile

AR=ar
CPP=g++
CPPFLAGS=-Wall -std=c++17 -O0 -g -Iinclude/
TARGET=name
OBJECTS=name.o

OBJDIR=obj
SRCDIR=src
BINDIR=lib

all: build

directories:
	@mkdir -p $(BINDIR)
	@mkdir -p $(OBJDIR)

$(OBJDIR)/%.o: $(SRCDIR)/%.cpp
	$(CPP) -c $(CPPFLAGS) $< -o $@

build: directories $(addprefix $(OBJDIR)/,$(OBJECTS))
	$(AR) rcs $(BINDIR)/lib$(TARGET).a $(addprefix $(OBJDIR)/, $(OBJECTS))

clean:
	$(RM) -r $(OBJDIR)/*
	$(RM) -r $(BINDIR)/*
	make -C tests clean

test: build
	make -C tests
