- name: Install Bazel Archlinux
  when: ansible_distribution == "Archlinux"
  block:
    - name: Install bazel
      become: true
      ansible.builtin.package:
        state: present
        name: bazel

- name: Install Bazel Ubuntu
  when: ansible_distribution == "Ubuntu"
  block:
    - name: Install apt dependencies
      become: true
      ansible.builtin.package:
        state: present
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    - name: Get DEB architecture
      ansible.builtin.command: dpkg --print-architecture
      register: deb_architecture
      changed_when: false

    - name: Get DEB release
      ansible.builtin.command: lsb_release -cs
      register: deb_release
      changed_when: false

    - name: Create keyrings directory
      become: true
      ansible.builtin.file:
        path: /usr/share/keyrings
        state: directory
        mode: "0755"

    - name: Install GPG key
      become: true
      ansible.builtin.shell: |
        curl -fsSL {{ bazel_key_url }} | gpg --dearmor -o {{ bazel_key_path }}
      args:
        creates: "{{ bazel_key_path }}"
      tags:
        - skip_ansible_lint

    - name: Apt source
      become: true
      block:
        - name: Remove bazel source file
          ansible.builtin.file:
            state: absent
            path: "{{ bazel_source_path }}"

        - name: Add bazel source file
          ansible.builtin.lineinfile:
            line: >
              deb [arch={{ deb_architecture.stdout }}
              signed-by={{ bazel_key_path }}]
              https://storage.googleapis.com/bazel-apt
              stable jdk1.8
            path: "{{ bazel_source_path }}"
            create: true
            owner: root
            group: root
            mode: "0644"

    - name: Update Apt Repositories
      become: true
      ansible.builtin.package:
        update_cache: true
      changed_when: false

    - name: Install Bazel
      become: true
      ansible.builtin.package:
        state: latest
        name: bazel
      tags:
        - skip_ansible_lint
