- name: Download installer
  ansible.builtin.get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "0755"
    force: true

- name: Install rustup
  ansible.builtin.command: /tmp/sh.rustup.rs -y
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/env"

- name: Install stable toolchain
  ansible.builtin.command: "{{ ansible_env.HOME }}/.cargo/bin/rustup toolchain install stable"
  args:
    creates: "{{ ansible_env.HOME }}/.rustup/toolchains/stable-*"

- name: Install beta toolchain
  ansible.builtin.command: "{{ ansible_env.HOME }}/.cargo/bin/rustup toolchain install beta"
  args:
    creates: "{{ ansible_env.HOME }}/.rustup/toolchains/beta-*"
