- name: Install Restic
  become: true
  ansible.builtin.package:
    state: present
    name: restic

- name: Create user systemd folder
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user"
    state: directory

- name: Copy backup service
  ansible.builtin.copy:
    src: backup.service
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/backup.service"

- name: Copy backup timer
  ansible.builtin.copy:
    src: backup.timer
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/backup.timer"

- name: Copy failure handler service
  ansible.builtin.copy:
    src: backup.service
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/failure-handler@.service"

- name: Link restic excludes
  ansible.builtin.file:
    src: "{{ role_path }}/files/restic_exclude"
    dest: "{{ ansible_env.HOME }}/.restic_exclude"
    state: link

- name: Create user local bin
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory

- name: Copy backup script
  ansible.builtin.copy:
    src: backup
    dest: "{{ ansible_env.HOME }}/.local/bin/"
    mode: 0755

- name: Enable backup timer
  ansible.builtin.systemd:
    name: backup.timer
    enabled: true
    scope: user
