- name: Install Python
  when: ansible_facts["distribution"] == "Archlinux"
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ python_arch_packages }}"

- name: Install Python
  when: ansible_facts["distribution"] == "Ubuntu"
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ python_ubuntu_packages }}"

- name: Install Pip Packages
  when: ansible_facts["distribution"] == "Ubuntu"
  ansible.builtin.pip:
    state: present
    name: "{{ python_pip_packages }}"
