- name: Keyboard repeat interval
  gsetting:
    settings:
      org.gnome.desktop.peripherals.keyboard.repeat-interval: "{{ keyboard.repeat | int }}"
  changed_when: false
  tags:
    - user_config

- name: Keyboard repeat delay
  gsetting:
    settings:
      org.gnome.desktop.peripherals.keyboard.delay: "{{ keyboard.delay | int }}"
  changed_when: false
  tags:
    - user_config

- name: Touchpad Speed
  gsetting:
    settings:
      org.gnome.desktop.peripherals.touchpad.speed: "{{ mouse.speed | float }}"
  changed_when: false
  tags:
    - user_config
