- name: Install Python
  when: ansible_distribution == "Archlinux"
  become: true
  package:
    state: latest
    name: python

- name: Install Python
  when: ansible_distribution == "Ubuntu"
  become: true
  package:
    state: latest
    name: "{{ ubuntu_packages }}"

- name: Install Pip Packages
  pip:
    state: present
    name: "{{ pip_packages }}"
