- name: Create Github User
  become: true
  ansible.builtin.user:
    name: github
    password_lock: true
    state: present
    comment: User owning GitHub SSH access / permissions

- name: Copy ssh keygen script
  become: true
  ansible.builtin.copy:
    src: gen_github_ssh_key.sh
    dest: "/home/github/gen_github_ssh_key.sh"
    owner: github
    group: github
    mode: "0644"
