- name: Create ~/.local/bin
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    recurse: true
    mode: "0755"
  tags:
    - user_config

- name: Add ~/.local/bin to PATH
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: export PATH="$HOME/.local/bin:$PATH"
    create: true
    mode: "0644"
  tags:
    - user_config
