- name: Install Arduino
  become: true
  ansible.builtin.package:
    state: present
    name:
      - arduino
      - arduino-avr-core
      - arduino-builder
      - arduino-cli
      - arduino-docs
      - arduino-language-server

- name: Add user to serial groups
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    append: true
    groups:
      - uucp
