- name: Install Restic
  become: true
  ansible.builtin.package:
    state: present
    name: restic

- name: Create user systemd folder
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user"
    state: directory
    mode: "0755"

- name: Copy service files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/{{ item }}"
    mode: "0644"
  loop:
    - backup.service
    - backup.timer

- name: Configure restic exclude
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.restic_exclude"
    block: "{{ lookup('file', 'restic_exclude') }}"
    create: true
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: "0644"

- name: Write restic password to file
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.restic_pass"
    content: "{{ restic_password | mandatory }}"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: "0400"

- name: Copy backup script
  ansible.builtin.copy:
    src: backup
    dest: "{{ ansible_env.HOME }}/.local/bin/"
    mode: "0755"

- name: Enable backup timer
  ansible.builtin.systemd:
    name: backup.timer
    daemon_reload: true
    enabled: true
    scope: user
