- name: Install Packages
  become: true
  package:
    state: latest
    name: "{{ packages }}"

- when: ansible_distribution == "Archlinux"
  block:
    - name: Clone Snap AUR
      git:
        repo: "{{ snapd_aur_url }}"
        dest: "{{ snapd_build_path }}"

    - name: Build Snap AUR
      shell: makepkg -si --noconfirm
      args:
        chdir: "{{ snapd_build_path }}"

    - name: Start Snap Service
      become: true
      systemd:
        name: snapd.socket
        state: started
        enabled: true

    - name: Link /snap
      become: true
      file:
        src: /var/lib/snapd/snap
        dest: /snap
        state: link
        mode: "0777"
        owner: root
        group: root

          #- name: Install Snap Apps
          #  become: true
          #  community.general.snap:
          #    state: present
          #    name: "{{ snap_packages }}"

- name: Install Snap Classic Apps
  become: true
  community.general.snap:
    state: present
    classic: true
    name: "{{ snap_classic_packages }}"

- name: Install Google Chrome
  become: true
  apt:
    deb: "{{ google_chrome_deb }}"
  when: ansible_distribution == "Ubuntu"

    #- include_role:
    #    name: neovim
