- name: Install mdadm
  become: true
  ansible.builtin.package:
    state: present
    name: mdadm

- name: Add user to raid group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: "{{ raid_user }}"
    append: true

- name: Create mount point
  become: true
  ansible.builtin.file:
    path: /data
    state: directory
    owner: "{{ raid_user }}"
    group: "{{ raid_user }}"
    mode: "0770"

- name: Examine array
  become: true
  ansible.builtin.shell: mdadm --examine --scan
  register: scan
  changed_when: false

- name: Reassemble array
  become: true
  ansible.builtin.lineinfile:
    path: /etc/mdadm/mdadm.conf
    line: "{{ scan.stdout }}"

- name: Add fstab entry
  become: true
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: '/dev/md127              /data   ext4            rw,relatime,nofail      0 2'

- name: Reload systemctl daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
