- name: Install Apprise
  become: true
  ansible.builtin.package:
    state: present
    name: apprise

- name: Create user systemd folder
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user"
    state: directory
    mode: "0755"

- name: Copy service files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/{{ item }}"
    mode: "0644"
  loop:
    - mail_system_report.service
    - mail_system_report.timer

- name: Copy script
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/"
    mode: "0755"
  loop:
    - mail_stats
    - mail_system_report

- name: Enable service timer
  ansible.builtin.systemd:
    name: mail_system_report.timer
    daemon_reload: true
    enabled: true
    scope: user
