- name: Install alacritty
  become: true
  ansible.builtin.package:
    state: present
    name: reflector
  when: ansible_distribution == "Archlinux"

- name: Copy config
  ansible.builtin.copy:
    src: reflector.conf
    dest: /etc/xdg/reflector
  when: ansible_distribution == "Archlinux"
