- tags:
    - user
  block:
  - name: Generate SSH Key
    shell: ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
    args:
      creates: ~/.ssh/id_rsa

  - name: Disable sudo password for user
    become: true
    lineinfile:
      path: "/etc/sudoers.d/{{ ansible_user_id }}"
      line: "{{ ansible_user_id }} ALL=(ALL) NOPASSWD: ALL"
      create: true
      owner: root
      group: root
      mode: "0644"

  - name: Keyboard repeat interval
    gsetting:
      settings:
        org.gnome.desktop.peripherals.keyboard.repeat-interval: "{{ keyboard.repeat | int }}"

  - name: Keyboard repeat delay
    gsetting:
      settings:
        org.gnome.desktop.peripherals.keyboard.delay: "{{ keyboard.delay | int }}"

  - name: Touchpad Speed
    gsetting:
      settings:
        org.gnome.desktop.peripherals.touchpad.speed: "{{ mouse.speed | float }}"
