- name: Create ~/.ssh directory
  file:
    path: "{{ ansible_env.HOME }}"
    state: directory
    mode: "0700"

- name: Create ~/.local/bin
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    recurse: true

- name: Generate SSH Key
  shell: ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
  args:
    creates: ~/.ssh/id_rsa

- name: Disable sudo password for user
  become: true
  lineinfile:
    path: "/etc/sudoers.d/{{ ansible_user_id }}"
    line: "{{ ansible_user_id }} ALL=(ALL) NOPASSWD: ALL"
    create: true
    owner: root
    group: root
    mode: "0644"
