- name: Create ~/.ssh directory
  ansible.builtin.package:
    path: "{{ ansible_env.HOME }}"
    state: directory
    mode: "0700"

- name: Create ~/.local/bin
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    recurse: true
    mode: "0755"

- name: Generate SSH Key
  shell: "ssh-keygen -b {{ ssh_key_size }} -t {{ ssh_key_type }} -f {{ ssh_key_path }} -q -N ''"
  args:
    creates: "{{ ssh_key_path }}"

- name: Disable sudo password for user
  become: true
  lineinfile:
    path: "/etc/sudoers.d/{{ ansible_user_id }}"
    line: "{{ ansible_user_id }} ALL=(ALL) NOPASSWD: ALL"
    create: true
    owner: root
    group: root
    mode: "0644"
