- name: install nvm
  shell: curl -o- {{ nvm_url }} | bash
  environment:
    NVM_DIR: ""
  args:
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: install node
  shell: . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install 16
  args:
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.nvm/versions/node"

- name: set node version
  shell: . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm use default 16
  args:
    executable: /bin/bash
