- name: Install NodeJS Archlinux
  when: ansible_distribution == "Archlinux"
  block:
    - name: Install packages
      become: true
      ansible.builtin.package:
        state: present
        name:
          - nodejs
          - npm
          - yarn

- name: Install NodeJS Ubuntu
  when: ansible_distribution == "Ubuntu"
  block:
    - name: Remove nodesource apt source
      become: true
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/nodesource.list
        state: absent

    - name: Update Apt Repositories
      become: true
      ansible.builtin.package:
        update_cache: true
      changed_when: false

    - name: Remove old node version
      become: true
      ansible.builtin.package:
        state: absent
        name:
          - nodejs
          - nodejs-doc

    - name: Download installer
      ansible.builtin.get_url:
        url: "https://deb.nodesource.com/setup_{{ node_version }}.x"
        dest: /tmp/node_setup.sh
        mode: "0755"
        force: true

    - name: Add node apt repo
      become: true
      ansible.builtin.command: /tmp/node_setup.sh
      tags:
        - skip_ansible_lint

    - name: Install node
      become: true
      ansible.builtin.package:
        state: latest
        name: nodejs
      tags:
        - skip_ansible_lint
