- name: Install Packages
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ packages }}"

- name: Install Flatpak
  become: true
  when: ansible_distribution == "Archlinux"
  ansible.builtin.package:
    state: present
    name: flatpak

- name: Install Flatpak Apps
  when: ansible_distribution == "Archlinux"
  community.general.flatpak:
    name: "{{ flatpak_packages }}"

- name: Install Snap Apps
  become: true
  when: ansible_distribution == "Ubuntu"
  community.general.snap:
    state: present
    name: "{{ snap_packages }}"

- name: Install Snap Classic Apps
  become: true
  when: ansible_distribution == "Ubuntu"
  community.general.snap:
    state: present
    classic: true
    name: "{{ snap_classic_packages }}"

- name: Install Google Chrome
  become: true
  ansible.builtin.package:
    deb: "{{ google_chrome_deb }}"
  when: ansible_distribution == "Ubuntu"
