- name: Color Output
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    search_string: "#Color"
    line: Color
    owner: root
    group: root
    mode: "0644"
  when: ansible_distribution == "Archlinux"

- name: Verbose Package List
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    search_string: "#VerbosePkgLists"
    line: VerbosePkgLists
    owner: root
    group: root
    mode: "0644"
  when: ansible_distribution == "Archlinux"

- name: Parallel Download
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: '^#ParallelDownloads\s*=\s*(\d+)$'
    line: 'ParallelDownloads = \1'
    backrefs: true
    owner: root
    group: root
    mode: "0644"
  when: ansible_distribution == "Archlinux"

- name: Multilib
  become: true
  ansible.builtin.replace:
    path: /etc/pacman.conf
    regexp: '#\[multilib\]\n#Include = /etc/pacman.d/mirrorlist'
    replace: "[multilib]\nInclude = /etc/pacman.d/mirrorlist"
    owner: root
    group: root
    mode: "0644"
  when: ansible_distribution == "Archlinux"
