#!/bin/bash

# Exit on failure with status code of failed command
set -e

if [ -z "$HOSTNAME" ]; then
    echo "environment variable HOSTNAME is empty, cannot continue"
    exit 1
fi

restic_remote="restic -v -p $HOME/.restic_pass -r sftp:tom-lan.local:/home/deepstorage/restic"
START_SECONDS=$SECONDS

RED="\e[0;31m"
GREEN="\e[0;32m"
YELLOW="\e[0;33m"
CYAN="\e[0;36m"
WHITE="\e[1;97m"
RESET="\e[0;0m"

echo -e "${CYAN}:: ${WHITE}Backing up\
    ${YELLOW}$HOSTNAME${WHITE}:${GREEN}$HOME${WHITE}\
    to ${YELLOW}tom-lan${WHITE}:${GREEN}/home/deepstorage/restic${RESET}"

notify-send -u low "Backup has started..."

$restic_remote backup\
    --exclude-file $HOME/.restic_exclude\
    $HOME\
    --tag $HOSTNAME

echo -e ${CYAN}:: ${WHITE}Finished in $(( SECONDS - START_SECONDS ))s!${RESET}

notify-send -u low "Backup has finished!"

