#!/usr/bin/env python3
from glob import glob
import random
from subprocess import call
from os.path import isfile, join
from datetime import datetime


PATH = '/home/thomas/wallpapers'
LOG = '/home/thomas/wallpapers/last.txt'
TYPES = ['png', 'gif', 'jpe', 'jpeg', 'jpg']
MODE = '--bg-fill'


def print_help():
    print('Usage: changewall [--help] <category> <filename>')


def rand(category = '*'):
    ''' Select a random file from the given `category` '''
    files = []
    for t in TYPES:
        path = join(PATH, '{}/*.{}'.format(category, t))
        files.extend(glob(path))
    return random.choice(files)


def now_timestamp():
    ''' Get the utc timestamp for now in UTC format '''
    now = datetime.now()
    return now.strftime('%Y-%m-%dT%H:%M:%SZ%Z')


def log(choice):
    ''' Log the choice to the file `LOG` with a utc timestamp '''
    with open(LOG, 'a') as fout:
        fout.write(now_timestamp())
        fout.write(' ')
        fout.write(choice)
        fout.write('\n')


def feh(file):
    ''' Call `feh` with the `MODE` flag and `file` '''
    call(['feh', MODE, file])
    #print('Called feh with', MODE, 'and', file)


def main(args):
    if len(args) == 0:
        file = rand()
    elif len(args) == 2:
        category = args[0]
        file = join(PATH, category, args[1])
    elif len(args) == 1:
        if args[0] == '--help':
            print_help()
            return
        else:
            category = args[0]
            file = rand(category)
    
    log(file)
    feh(file)


if __name__ == '__main__':
    import sys
    main(sys.argv[1:])

