#!/usr/bin/env python3
from glob import glob
import random
from subprocess import call
from os.path import isfile, join
from datetime import datetime

PATH = '/home/thomas/wallpapers'
TYPES = ['png', 'gif', 'jpe', 'jpeg', 'jpg']
MODE = '--bg-fill'

# Usage: changewall [--help] <category> <filename>
# Note if you do not provide a category, one will be selected at random.
# You may not provide a filename without first providing a category


def scan_dir(category):
    files = []

    for t in TYPES:
        path = join(PATH, '{}/*.{}'.format(category, t))
        files.extend(glob(path))
    
    choice = random.choice(files)
    return choice


def now_timestamp():
    now = datetime.now()
    return now.strftime('%Y-%m-%dT%H:%M:%SZ%Z')


def log_choice(choice):
    with open('/home/thomas/wallpapers/last.txt', 'a') as fout:
        fout.write(now_timestamp())
        fout.write(' ')
        fout.write(choice)
        fout.write('\n')
 

def main(argv):
    category = '*'
    choice = None
    file = None

    if len(argv) > 1:
        if argv[1] == '--help':
            print('Usage: changewall [--help] <category> <filename>')
            return
        category = argv[1]
    
    if len(argv) > 2:
        file = argv[2]

        if isfile(join(PATH, '{}/{}'.format(category, file))):
            choice = join(PATH, '{}/{}'.format(category, file))
        else:
            print('File does not exist {}/{}'.format(category, file))
            return

    if not choice:
        choice = scan_dir(category)

    log_choice(choice)
    call(['feh', MODE, choice])


if __name__ == '__main__':
    import sys
    main(sys.argv)

