#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 <l/d>"
    echo ""
    echo "    l | light   light mode"
    echo "    g | gray    light windows w/ dark terminal"
    echo "    d | dark    dark mode"
    exit 0
fi

case $1 in
    l|light) WIN=light;TERM=light;;
    g|gray) WIN=light;TERM=dark;;
    d|dark) WIN=dark;TERM=dark;;
    *) exit 1;;
esac

echo $TERM > ~/.last_background
cinnamon_theme $WIN
ln -sf ~/.config/termite/one$TERM ~/.config/termite/config
#ln -sf ~/.config/termite/termite-colors-solarized/solarized-$TERM ~/.config/termite/config
source ~/.bashrc
killall -USR1 termite

