#!/usr/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 <l/d>"
    echo ""
    echo "    l | light   light mode"
    echo "    d | dark    dark mode"
    exit 0
fi

LIGHT="Mint-Y-Blue"
LIGHTBORDER="Mint-Y"
DARK="Mint-Y-Dark-Blue"
DARKBORDER="Mint-Y-Dark"

case $1 in
    l|light) CURRENT=$LIGHT; CURRENTBORDER=$LIGHTBORDER;;
    d|dark) CURRENT=$DARK; CURRENTBORDER=$DARKBORDER;;
    *) exit 1;;
esac

gsettings set org.cinnamon.desktop.interface icon-theme $CURRENT
gsettings set org.cinnamon.desktop.interface gtk-theme $CURRENT
gsettings set org.cinnamon.theme name $CURRENT
gsettings set org.cinnamon.desktop.wm.preferences theme $CURRENTBORDER

