#!/bin/bash

# Exit on failure with status code of failed command
set -e

if [ -z "$HOSTNAME" ]; then
    echo "environment variable HOSTNAME is empty, cannot continue"
    exit 1
fi

RED="\e[0;31m"
GREEN="\e[0;32m"
YELLOW="\e[0;33m"
CYAN="\e[0;36m"
WHITE="\e[1;97m"
RESET="\e[0;0m"

restic_remote="restic -v -p $HOME/.restic_pass -r sftp:tom-lan.local:/home/deepstorage/restic"

echo -e ${CYAN}:: ${WHITE}Cleaning backups for ${YELLOW}$HOSTNAME${WHITE}:${GREEN}$HOME${WHITE} to ${YELLOW}tom-lan${WHITE}:${GREEN}/home/deepstorage/restic${RESET}
echo -e Keep\
    ${RED}3${WHITE} hourly\
    ${RED}7${WHITE} daily\
    ${RED}5${WHITE} weekly\
    ${RED}12${WHITE} monthly\
    ${RED}50${WHITE} yearly${RESET}

START_SECONDS=$SECONDS

$restic_remote forget\
    --tag $HOSTNAME\
    --keep-hourly 3\
    --keep-daily 7\
    --keep-weekly 5\
    --keep-monthly 12\
    --keep-yearly 50

$restic_remote prune

echo -e ${CYAN}:: ${WHITE}Finished in $(( SECONDS - START_SECONDS ))s!${RESET}

