#!/bin/bash

if [ $# -ne 2 ]; then
    echo "Usage: $0 <group> <path>"
    echo "This program converts a file structure at path to be owned by a group."
    echo "It also removes permissions for other users and set the default acl"
    echo "for other users to 0."
    exit 1
fi

GROUP_IN=$1
PATH_IN=$2

read -p "Reset acl for $PATH_IN? [y/N] " yn
case $yn in
	[Yy]* ) sudo setfacl -Rb $PATH_IN;;
    * ) ;;
esac

read -p "Reset x for $PATH_IN? [y/N] " yn
case $yn in
	[Yy]* ) sudo chmod -R u-x,g-x $PATH_IN;;
    * ) ;;
esac

sudo chown -R :$GROUP_IN $PATH_IN
sudo chmod -R u+rw,g+rw,o= $PATH_IN
sudo find $PATH_IN -type d -exec chmod u+x,g+xs "{}" ";"
sudo setfacl -Rdm o:0 $PATH_IN

