#!/bin/bash

TARDIR=$HOME/dotfiles/templates

## Print usage message
usage() {
	echo "Usage: mkn [options] language name"
	echo
    ls -1 $TARDIR
    echo
	echo "Options:"
	echo "    -h|--help     Display this help message"
}

## Clean the language string
clean_lang() {
	local LANG=$(echo "$1" | tr '[:upper:]' '[:lower:]')
	if [ "cpp" == "$LANG" ] || [ "c++" == "$LANG" ] || [ "cxx" == "$LANG" ]
	then
		echo "cpp"
	elif [ "python" == "$LANG" ] || [ "py" == "$LANG" ]
	then
		echo "py"
	else
		echo "$LANG"
	fi
}

## GetOpt parse
SHORT=h
LONG=help
OPTS=$(getopt -o $SHORT --long $LONG --name "$0" -- "$@")

## Check for parse errors
if [ $? != 0 ]; then echo "Parsing failed, exiting." >&2; exit 1; fi

eval set -- "$OPTS"

## Read optional args
while true
do
	case "$1" in
		-h|--help) usage; exit 0;;
		--) shift; break;;
		-*) echo "unknown option: $1" >&2; usage; exit 1;;
	esac
done

## Read positional args
PLANG=$(clean_lang "$1")
shift
NAME="$1"
shift

## Check for required positional arg
if [ -z "$PLANG" ]; then usage; exit 1; fi

## Check for required positional arg
if [ -z "$NAME" ]; then usage; exit 1; fi

# Make sure directory does not exist
if [ -d "$NAME" ]; then echo "Failed to create project, directory already exists."; exit 1; fi

## Check that a template exists
PTYPE=$PLANG
ARCHIVE=$TARDIR/$PTYPE
if [ ! -d "$ARCHIVE" ]; then echo "Unknown project type $PTYPE"; exit 1; fi

echo Making new project $NAME in $PLANG

## Check that we are not writing over a project
if [[ -f .mk ]]; then
	echo Project $NAME already exists!
	exit -1
fi

## Expand template into current workind directory
#cp -r $ARCHIVE/* ./
cp -r $ARCHIVE ./$NAME

# Move into project directory
cd $NAME

if [ -f ".mk" ]; then
    ## Run setup script if there is one
    ./.mk

    ## Remove setup script to reset permissions
    rm ./.mk
fi

## Initialize git repo
git init
touch gitignore
mv gitignore .gitignore
git add .
git commit -m "First Commit"

