- name: Create RAID User
  become: true
  ansible.builtin.user:
    name: "{{ raid_user }}"
    password_lock: true
    system: true
    state: present
    shell: /usr/bin/nologin
    comment: User owning /data raid mount
