#!/bin/bash

GMAIL_PASSWD=$(cat "$HOME/.ssh/apprise_tom-lan.txt")

if [ -z "$GMAIL_PASSWD" ]; then
    echo Gmail password is empty, cannot send emails!
    exit 1
fi

APPRISE_TARGET="mailto://theharrisoncrafter+alerts:$GMAIL_PASSWD@gmail.com"

apprise -vv -t "Status" $APPRISE_TARGET <<EOF
This is your status report
EOF
