- name: Install Virtualbox Archlinux
  when: ansible_distribution == "Archlinux"
  block:
    - name: Install virtualbox
      become: true
      ansible.builtin.fail:
        msg: You haven't added the Archlinux steps for Virtualbox

- name: Install Virtualbox Ubuntu
  when: ansible_distribution == "Ubuntu"
  block:
    - name: Install apt dependencies
      become: true
      ansible.builtin.package:
        state: present
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    - name: Get DEB architecture
      ansible.builtin.command: dpkg --print-architecture
      register: deb_architecture
      changed_when: false

    - name: Get DEB release
      ansible.builtin.command: lsb_release -cs
      register: deb_release
      changed_when: false

    - name: Create keyrings directory
      become: true
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Install GPG key
      become: true
      ansible.builtin.shell: |
        curl -fsSL {{ virtualbox_key_url }} | gpg --dearmor -o {{ virtualbox_key_path }}
      args:
        creates: "{{ virtualbox_key_path }}"
      tags:
        - skip_ansible_lint

    - name: Apt source
      become: true
      block:
        - name: Remove virtualbox source file
          ansible.builtin.file:
            state: absent
            path: "{{ virtualbox_source_path }}"

        - name: Add virtualbox source file
          ansible.builtin.lineinfile:
            line: >
              deb [arch={{ deb_architecture.stdout }}
              signed-by={{ virtualbox_key_path }}] https://download.virtualbox.org/virtualbox/debian
              {{ deb_release.stdout }} contrib
            path: "{{ virtualbox_source_path }}"
            create: true
            owner: root
            group: root
            mode: "0644"

    - name: Update Apt Repositories
      become: true
      ansible.builtin.package:
        update_cache: true
      changed_when: false

    - name: Install Virtualbox
      become: true
      ansible.builtin.package:
        state: latest
        name: virtualbox-7.0
      tags:
        - skip_ansible_lint

- name: Add user to vboxuser group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: vboxusers
    append: true
