- name: Install Docker Archlinux
  when: ansible_distribution == "Archlinux"
  block:
    - name: Install docker
      become: true
      ansible.builtin.package:
        state: present
        name:
          - docker
          - docker-compose

- name: Install Docker Ubuntu
  when: ansible_distribution == "Ubuntu"
  block:
    - name: Install apt dependencies
      become: true
      ansible.builtin.package:
        state: present
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    - name: Get DEB architecture
      ansible.builtin.shell: dpkg --print-architecture
      register: deb_architecture
      changed_when: false

    - name: Get DEB release
      ansible.builtin.shell: lsb_release -cs
      register: deb_release
      changed_when: false

    - name: Create keyrings directory
      become: true
      ansible.builtin.package:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Install GPG key
      become: true
      ansible.builtin.shell: |
        curl -fsSL {{ docker_key_url }} | gpg --dearmor -o {{ docker_key_path }}
      args:
        creates: "{{ docker_key_path }}"

    - name: Add deb source
      become: true
      ansible.builtin.lineinfile:
        line: >
          "deb [arch={{ deb_architecture.stdout }}"
          "signed-by={{ docker_key_path }}] https://download.docker.com/linux/ubuntu"
          "{{ deb_release.stdout }} stable"
        path: "{{ docker_source_path }}"
        create: true
        owner: root
        group: root
        mode: "0644"

    - name: Update Apt Repositories
      become: true
      ansible.builtin.package:
        update_cache: true
      changed_when: false

    - name: Install Docker
      become: true
      ansible.builtin.package:
        state: present
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
          - docker-compose-plugin

- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true
