- name: Remove old docker-compose
  become: true
  ansible.builtin.package:
    state: absent
    name: docker-compose
  changed_when: false

- name: Install Docker Archlinux
  when: ansible_distribution == "Archlinux"
  block:
    - name: Install docker
      become: true
      ansible.builtin.package:
        state: present
        name:
          - docker
          - docker-compose

- name: Install Docker Ubuntu
  when: ansible_distribution == "Ubuntu"
  block:
    - name: Install apt dependencies
      become: true
      ansible.builtin.package:
        state: present
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    - name: Get DEB architecture
      ansible.builtin.command: dpkg --print-architecture
      register: deb_architecture
      changed_when: false

    - name: Get DEB release
      ansible.builtin.command: lsb_release -cs
      register: deb_release
      changed_when: false

    - name: Create keyrings directory
      become: true
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Install GPG key
      become: true
      ansible.builtin.shell: |
        curl -fsSL {{ docker_key_url }} | gpg --dearmor -o {{ docker_key_path }}
      args:
        creates: "{{ docker_key_path }}"
      tags:
        - skip_ansible_lint

    - name: Apt source
      become: true
      block:
        - name: Stat source file
          ansible.builtin.stat:
            path: "{{ docker_source_path }}"
          register: st

        - name: Remove docker source file
          ansible.builtin.file:
            state: absent
            path: "{{ docker_source_path }}"
          changed_when: false

        - name: Add docker source file
          ansible.builtin.lineinfile:
            line: >
              deb [arch={{ deb_architecture.stdout }}
              signed-by={{ docker_key_path }}] https://download.docker.com/linux/ubuntu
              {{ deb_release.stdout }} stable
            path: "{{ docker_source_path }}"
            create: true
            owner: root
            group: root
            mode: "0644"
          changed_when: not st.stat.exists

    - name: Update Apt Repositories
      become: true
      ansible.builtin.package:
        update_cache: true
      changed_when: false

    - name: Install Docker
      become: true
      ansible.builtin.package:
        state: latest
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
      tags:
        - skip_ansible_lint

- name: Add user to docker group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true

- name: Start docker service
  become: true
  ansible.builtin.systemd:
    state: started
    name: docker
    enabled: true
