- name: Install neovim
  become: true
  ansible.builtin.package:
    name: neovim
    state: present
  when: ansible_distribution == "Archlinux"

- name: Install neovim
  become: true
  community.general.snap:
    name: nvim
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install Config
  ansible.builtin.git:
    repo: "{{ neovim_config_git_url }}"
    dest: "{{ neovim_config_path }}"
  tags:
    - user_config
    - skip_ansible_lint

- name: Plugged Install
  ansible.builtin.command: "nvim +'PlugInstall --sync' +qa"
  args:
    creates: "{{ neovim_config_path }}/plugged"
  tags:
    - user_config

- name: CoC Install
  ansible.builtin.command: "nvim +'CocInstall' +qa"
  args:
    creates: "{{ neovim_config_path }}/plugged/coc.nvim/node_modules/"
  tags:
    - user_config

- name: Override .vim
  ansible.builtin.file:
    src: "{{ neovim_config_path }}"
    dest: "{{ ansible_env.HOME }}/.vim"
    state: link
    mode: 0755
  tags:
    - user_config

- name: Override .vimrc
  ansible.builtin.file:
    src: "{{ neovim_config_path }}/init.vim"
    dest: "{{ ansible_env.HOME }}/.vimrc"
    state: link
    mode: 0755
  tags:
    - user_config
