- name: Install neovim
  become: true
  ansible.builtin.package:
    name: neovim
    state: present
  when: ansible_distribution == "Archlinux"

- name: Install neovim
  become: true
  community.general.snap:
    name: nvim
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Plugged Install
  ansible.builtin.command: "nvim +'PlugInstall --sync' +qa"
  args:
    creates: "{{ ansible_env.HOME }}/.config/nvim/plugged"
  tags:
    - user_config

- name: CoC Install
  ansible.builtin.command: "nvim +'CocInstall' +qa"
  args:
    creates: "{{ ansible_env.HOME }}/.config/nvim/plugged/coc.nvim/node_modules/"
  tags:
    - user_config
