name: ci

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "2.1.2"

      - name: Install Dependencies
        run: pip install yamllint

      - name: Lint
        run: yamllint -c yamllint.yml .

  increment_version:
    name: Increment Version
    uses: automas-dev/reusable-workflows/.github/workflows/increment_version.yml@v1.1
    secrets: inherit
    with:
      dry-run: ${{ github.ref == 'refs/heads/main' }}

    needs: [lint]

    permissions:
      contents: write
